spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # auto-update schema (optional)
    show-sql: true      # SQL 쿼리 출력 (optional)
    properties:
      hibernate:
        format_sql: true # SQL 포맷팅 (optional)
  # 파일 업로드 설정
  servlet:
    multipart:
      enabled: true                 # multipart 업로드 기능 활성화
      max-file-size: 10MB           # 최대 파일 크기 설정
      max-request-size: 10MB        # 최대 요청 크기 설정
      file-size-threshold: 2KB      # 파일을 디스크에 저장하기 전에 메모리에 보관할 최소 크기 설정

#file:
#  upload-dir: ${UPLOAD_DIR}